name: 'auto-ci'
description: 'CI for monorepo based Node project'
inputs:
  configPath:
    description: 'path to config file'
    required: true
  modulesDir:
    description: 'the general directory which stores all modules'
    required: false
    default: ''

  #milliseconds:  # id of input
    #description: 'number of milliseconds to wait'
    #required: true
    #default: '1000'
#outputs:
  #time: # output will be available to future steps
    #description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'award'  
  color: 'green'
